import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'getting-started',
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {
        type: 'generated-index',
        slug: 'adr',
        description: 'Design decisions and rationale for the decisions-cc project.',
      },
      items: [{type: 'autogenerated', dirName: 'adr'}],
    },
  ],
};

export default sidebars;
