name: Publish to Verdaccio

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun run build

      - name: Publish to Verdaccio
        run: bun publish --registry https://npm.span.land
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.VERDACCIO_AUTH_TOKEN }}
